spring.profiles.active: dev
feed.filename: demo.feed

---

spring:
  profiles: dev
debug: true

audit:
  amount:
    deposit: 99
    withdrawal: 99

---

spring:
  profiles: prod
debug: false


